recipes-kernel/linux/linux-riscv_4.17.bb

linux: Update to the 4.17 kernel

---

conf/machine/freedom-u540.conf
conf/machine/qemuriscv64.conf

machine: Use the RISC-V 4.17 kernel

---

recipes-kernel/perf/perf.bbappend

These changes are in OE-Core now

perf: Delete bbappend

---

recipes-support/libgpg-error/files/0001-syscfg-Add-a-riscv32-architecture.patch

libgpg-error: Update patch upstream status

---

recipes-core/glibc/glibc-initial_%.bbappend
recipes-core/glibc/glibc_%.bbappend

glibc: Update the glibc fork to the latest submitted patch series

---

conf/machine/freedom-u540.conf
conf/machine/include/qemuriscv.inc

machine: Allow overriding TCLIBC

---

recipes-devtools/gdb/gdb-riscv.inc

Update to the latest version of the GDB.
Signed-off-by: pino-kim <sungwon.pino@gmail.com>

gdb: Update to the latest version

---

README.md
wic/freedom-u540-bbl.wks

README.md: Add more details for wic create

---

recipes-core/musl/musl/0001-RISC-V-add-riscv32-and-riscv64-architecture-support.patch

Update risc-v support patch past 1.1.21 release

---

conf/machine/baremetal-riscv32.conf
conf/machine/baremetal-riscv64.conf

baremetal-riscv: Remove BBL

---

recipes-dbs/mariadb/mariadb/0001-libmysql-Do-not-export-_fini-_init-on-risc-v.patch
recipes-dbs/mariadb/mariadb_5%.bbappend

mariadb: Fix build issues on risc-v

---

docs/Plasma-Mobile-on-Unleashed.md

docs: Add information on building Plasma Mobile for RISC-V

---

conf/layer.conf
dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
dynamic-layers/qt5-layer/recipes-qt/qt5/qtdeclarative_%.bbappend

Fix qtbase

---

docs/Plasma-Mobile-on-Unleashed.md

docs: Update the Plasma Mobile docs

---

conf/machine/include/qemuriscv.inc

qemuriscv: Allow overriding RISCV_SBI_PLAT

---

recipes-kernel/linux/files/0001-Revert-riscv-Use-latest-system-call-ABI.patch
recipes-kernel/linux/linux-mainline_5.1.bb

linux-mainline: Fix the 32-bit boot

---

recipes-kernel/linux/linux-mainline_5.1.bb
recipes-kernel/linux/linux-riscv-common.inc
recipes-kernel/linux/linux-riscv_5.0.bb

linux-mainline: Use the new 32-bit defconfig in Linux 5.1

---

recipes-bsp/u-boot/u-boot_2019.04.bbappend

u-boot: Check if ${UBOOT_ENV}.txt exists before using it

---

conf/layer.conf

layer.conf: Mark master warrior and newer compatible only

---

setup.sh

Minor fix.
Changed to be buildable according to input of each MACHINE.
Add buildable machine's information in script.
Signed-off-by: sungwon.pino <sungwon.pino@gmail.com>

setup.sh: Changed to be buildable according to input of each MACHINE

---

recipes-bsp/u-boot/files/tftp-mmc-boot.txt

u-boot: Run the boomcmd if we load a uEnv.txt file

---

README.md
docs/Plasma-Mobile-on-Unleashed.md

Fix minor typos in README.md and docs/Plasma-Mobile-on-Unleashed.md.
Signed-off-by: Vijai Kumar K <vijaikumar.kanagarajan@gmail.com>

Fix some minor typos in documentation

---

conf/layer.conf

Fixes: https://github.com/riscv/meta-riscv/issues/182

layer.conf: Mark as compatible with zeus

---

setup.sh

Fix typo in help message in setup.sh

---

conf/machine/baremetal-riscv32.conf
conf/machine/baremetal-riscv64.conf

machine/baremetal: Cleanup the baremetal code

---

recipes-core/glibc/glibc_%.bbappend

glibc: Update the RV32 glibc port

---

recipes-graphics/mesa/mesa/rv32-sys-futex.patch
recipes-graphics/mesa/mesa_19.%.bbappend
recipes-graphics/xorg-lib/libxshmfence/rv32_sys_futex.patch
recipes-graphics/xorg-lib/libxshmfence_1.3.bbappend

Helps these nosy apps build
Fixes #201

mesa,libxshmfence: Define __NR_futex for rv32

---

.travis.yml

.travis.yml: Update the Ubuntu distro

---

recipes-core/init-ifupdown/files/qemuriscv64/interfaces
recipes-core/init-ifupdown/init-ifupdown_%.bbappend

init-ifupdown: Remove the qemuriscv64 specific ifupdown script

---

CONTRIBUTORS
LICENSE

The list of people was generated with:
git log | grep Signed | sort | uniq
Also update the LICENSE file to point to the new file.

Add a CONTRIBUTORS file

---

README.md

Signed-off-by: sungwon.pino <sungwon.pino@gmail.com>

README.md: Minor fix to using wayland image for HiFive Unleashed board

---

dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd/0001-bitbang-Make-bitbang_swd-extern-definition.patch
dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd_riscv.bb

openocd: Fix build with gcc10/-fno-common

---

recipes-graphics/mesa/mesa/rv32-sys-futex.patch

Signed-off-by: sungwon.pino <sungwon.pino@gmail.com>

mesa : Fix patch-fuzz waring message when build qemuriscv32

---

recipes-core/musl/musl/0017-Add-bits-reg.h-for-riscv32.patch
recipes-core/musl/musl_%.bbappend

musl: Add bits/reg.h for riscv32

---

recipes-kernel/linux/files/0001-RV32-doesn-t-support-2GB-physical-memory-yet.patch
recipes-kernel/linux/linux-yocto_5.%.bbappend

linux-yocto: Fix 5.10.12+ build issue on rv32

---

conf/layer.conf

layer.conf: Drop gatesgarth from LAYERSERIES_COMPAT

---

recipes-kernel/firmware/linux-firmware-beaglev-bcm43430.bb
recipes-kernel/linux/linux-starfive-dev.bb
recipes-kernel/linux/linux-starfive/0001-riscv-Use-mno-relax-when-using-lld-linker.patch
recipes-kernel/linux/linux-starfive_5.12.bb
wic/beaglev.wks

this should help get these blobs into any kernel

package wifi/bt firmware via a recipe of its own

---

recipes-kernel/linux/linux-starfive-dev.bb

linux-starfive-dev: Dev has now moved to 5.14 for version

---

conf/layer.conf

apitrace: Skip textrel QA error

---

conf/layer.conf
recipes-support/libseccomp/libseccomp_%.bbappend

its not going to be backward ABI compatible with honister due to variable renaming.

layers: Bump to use kirkstone

---

recipes-kernel/firmware/linux-firmware-beaglev-bcm43430.bb

linux-firmware-beaglev-bcm43430: Update SRC_URIs for brcm firmware

---

recipes-devtools/riscv-tools/riscv-fesvr.bb
recipes-devtools/riscv-tools/riscv-spike.bb
recipes-kernel/linux/linux-mainline-common.inc

recipes: Use SPDX naming convention for LICENSE

---

recipes-bsp/boot0/boot0.bb

its not interesting for other machines yet

boot0: Pin to nezha-allwinner-d1

---

dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd_riscv.bb

openocd_riscv: Specify branch parameter to SRC_URI

---

setup.sh

This feature is deprecated and removed

setup.sh: Drop setting largefile in DISTRO_FEATURES

---

recipes-bsp/u-boot/u-boot-starfive_v2021.04.bb
recipes-kernel/linux/linux-starfive-dev.bb

u-boot-starfive: Update the branch name for beagleV

---

conf/layer.conf

vulkan-cts: Skip textrel QA check

---

docs/AE350-AX45MP.md

Update the AE350-AX45MP documentation

docs/AE350-AX45MP.md: Update kernel version

---

conf/layer.conf

pcsc-lite: Disable textrel QA check

---

conf/layer.conf

pcsc-lite: Ignore textrel on rv32

---

conf/machine/freedom-u540.conf

This is a collection of fixes to the OpenSBI build failures for the SiFive HiFive Unleashed board. This should fix: https://github.com/riscv/meta-riscv/issues/381

freedom-u540: OpenSBI build fixes

---

README.md
conf/machine/mangopi-mq-pro.conf
recipes-bsp/u-boot/u-boot-nezha.bb
recipes-kernel/linux/linux-nezha-dev.bb
recipes-kernel/rtl8723ds-mod/rtl8723ds.bb
recipes-kernel/rtl8723ds-mod/rtl8723ds/0001-Makefile-Add-modules_install-chain-and-make-KSRC-ass.patch

rtl8723ds-mod: Added wifi driver 
mangopi-mq-pro.conf: Added machine conf based on nezha-allwinner-d1.conf
Add support of the board to meta-riscv and poky
**-Signed-off-by: Pavel Zhukov <pavel@zhukoff.net>

Add MangoPi MQ Pro board config

---

conf/layer.conf
licenses/ChipsMedia_VisionFive2
recipes-bsp/opensbi/opensbi_%.bbappend

Fixes https://github.com/riscv/meta-riscv/issues/411

Add ChipsMedia_VisionFive2 license and fix opensbi builds for visionfive2

---

recipes-core/musl/musl/0001-riscv32-fix-inconsistent-ucontext_t-struct-tag.patch
recipes-core/musl/musl/0007-Emulate-wait4-using-waitid.patch
recipes-core/musl/musl/0008-riscv-Fall-back-to-syscall-__riscv_flush_icache.patch
recipes-core/musl/musl/0009-riscv32-Target-and-subtarget-detection.patch
recipes-core/musl/musl/0010-riscv32-add-arch-headers.patch
recipes-core/musl/musl/0011-riscv32-Add-fenv-and-math.patch
recipes-core/musl/musl/0012-riscv32-Add-dlsym.patch
recipes-core/musl/musl/0013-riscv32-Add-jmp_buf-and-sigreturn.patch
recipes-core/musl/musl/0014-riscv32-Add-thread-support.patch
recipes-core/musl/musl/0015-Change-definitions-of-F_GETLK-F_SETLK-F_SETLKW.patch
recipes-core/musl/musl/0016-riscv32-Wire-new-syscalls.patch
recipes-core/musl/musl/0017-Add-bits-reg.h-for-riscv32.patch

musl: Add patch header entries for SOB and status

---

setup.sh
tools/manifests/riscv-yocto.xml

Use new way to specify init manager.
Fixes https://github.com/riscv/meta-riscv/issues/434

setup.sh: Add usrmerge to DISTRO_FEATURES

---

recipes-bsp/common/visionfive2-firmware.inc
recipes-kernel/linux/linux-starfive-dev.bb

Tested on device with full running Plasma Desktop setup.

Visionfive2 update to SDK 3.7.5

---

kas/milkv-duo.yml

Added support for **milkv-duo** in kas yml file 
**-Signed-off-by: Phanirajkiran Mallapuram <phanirajkiran.a@gmail.com>**

Add support for milkv-duo board

---

recipes-core/musl/musl_%.bbappend

We carry in-progress patches to support it here.

musl: Add rv32 to supported hosts

---

recipes-core/musl/musl_%.bbappend

Otherwise it triggers parsing errors now with glibc

musl: Make compatible host glob musl specific

---

conf/layer.conf

ostree: Do not mark unavailable for rv32

---

recipes-kernel/linux/linux-starfive-dev.bb
recipes-kernel/linux/linux-starfive/0001-perf-cpumap-Make-counter-as-unsigned-ints.patch

Fixes https://github.com/riscv/meta-riscv/issues/457

linux-starfive-dev: Fix perf build with gcc-13

---

conf/machine/include/riscv-common.inc

This rename is needed to match change in repository upstream [1]
[1] https://lists.openembedded.org/g/openembedded-core/message/196617

riscv-common: Rename bmap-tools-native -> bmaptool-native

---

conf/layer.conf

layer.conf: Update to walnascar (5.2) layer/release series

---

tools/manifests/riscv-yocto.xml

manifests/riscv-yocto.xml: Use scarthgap branches for all repos

---

recipes-kernel/linux/linux-beaglev-dev/0001-dt-bindings-reset-Document-th1520-reset-control.patch
recipes-kernel/linux/linux-beaglev-dev/0002-reset-Add-th1520-reset-driver-support.patch
recipes-kernel/linux/linux-beaglev-dev/0003-WIP-on-th_net-d3e1832c7d2d-riscv-mm-update-T-Head-me.patch
recipes-kernel/linux/linux-beaglev-dev/0004-dt-binding-riscv-add-T-HEAD-CPU-reset.patch
recipes-kernel/linux/linux-beaglev-dev/0005-th1520-add-cpu-reset-node.patch
recipes-kernel/linux/linux-beaglev-dev/0006-th1520-beaglev-ahead.dts-enable-ethernet0.patch
recipes-kernel/linux/linux-beaglev-dev/0007-v6.8-rc3-fix-reset-th1520.c-build.patch

linux-beaglev-dev: Add missing upstream status to patches

---

recipes-graphics/wayland/weston/0006-libweston-reduce-checks-for-dmabufs-with-DRM-modifie.patch

weston: Port the patch to weston 14

---

conf/machine/visionfive2.conf
recipes-bsp/u-boot/u-boot_%.bbappend

Latest u-boot is building multiple DTBs

u-boot: Adjust for new location of DTB in 2025.04 release

---

conf/layer.conf

Since there are currently multiple breaking changes, update to a new release series for the next release so layers can show compatibility correctly.

layer.conf: Update to whinlatter release series

---

conf/machine/beaglev-ahead.conf
recipes-bsp/opensbi/opensbi-revyos/0001-add-missing-LDFLAGS-to-Makefile.patch
recipes-bsp/opensbi/opensbi-revyos/0001-c23-compatibility.patch
recipes-bsp/opensbi/opensbi-revyos_git.bb
recipes-bsp/opensbi/opensbi_%.bbappend

opensbi-revyos is an opensbi fork, specific for beaglev-ahead MACHINE.
this patch was originally authored by @OldManYellsAtCloud, but as per the discussion on the mailing list[1], I am taking it up and filing the PR.
[1] https://lists.yoctoproject.org/g/yocto/message/65466

opensbi-revyos: add recipe

---

recipes-graphics/mesa/mesa-pvr-riscv.inc

OE-core has started doing this for mesa with commit https://git.openembedded.org/openembedded-core/commit/?id=6f01f029ef6fed96e257d6a88de42edaa437de3e

mesa-pvr-riscv: Provide virtuals for vulkan and opencl drivers
