riscv/meta-riscv

conf/machine/qemuriscv64.conf
The 4.16 kernel doesn't currently seem to be able to come up to a login
prompt. Set the default to 4.15 (which can) for the time-being.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
=> qemuriscv64: pin kernel to 4.15

conf/machine/freedom-u540.conf, recipes-core/images/riscv-initramfs-image.bb, wic/freedom-u540-bbl.wks
The WIC image is modeled after what is created in the Buildroot based freedom-u-sdk. The bbl.bin file is written to the first part and rootfs image is written to second.
WIC is enabled  by default on the freedom-u540 machine. `bbl.bin` will in this case be a Linux kernel with a bundled initramfs image and initially the rootfs part even if written will not be utilized but one can chroot to it once the initramfs boots. 
The image layout
```
$ fdisk -l free.img 
Disk free.img: 1.3 GiB, 1416853504 bytes, 2767292 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 18B6DAA8-A99C-4E14-9239-3D3A15D168F5
Device     Start     End Sectors  Size Type
free.img1     34 …
```
=> WIC image support

conf/machine/freedom-u540.conf, conf/machine/qemuriscv64.conf
It is useful to be able to override kernel's provider or version from
local.conf.
For qemuriscv64 machine move PREFERRED_* variables before qemu.inc,
because it sets PREFERRED_PROVIDER to linux-yocto.
Signed-off-by: Taras Kondratiuk <takondra@cisco.com>
=> machine: allow to override kernel's provider/version

recipes-devtools/rpm/rpm_%.bbappend
beecrypt is no longer included in OE-core (since fb8ca4225f beecrypt:
remove) so remove our dependency on it.
=> recipes-devtools/rpm: Remove the beecrypt dependency

recipes-devtools/riscv-tools/riscv-pk.bb
bbl_payload requires the kernel deployed artifacts (e.g. vmlinux) during
compile time in order to generate the final bbl binary, so add
virtual/kernel:do_deploy as a do_compile dependency to get the
dependency task in the expected order.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
=> riscv-pk: depend on virtual/kernel:do_deploy

recipes-devtools/qemu/qemu_riscv.bb
8dad5ee5a63889fb8cb965df23a8101b12786e68 is not available anymore in riscv-qemu, so update to the latest revision available.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>
=> qemu-riscv: update to the latest

recipes-devtools/gdb/files/0001-linux-ptrace-Fix-RISC-V-cross-compilation-error.patch, recipes-devtools/gdb/gdb-riscv.inc, recipes-devtools/gdb/gdb_riscv.bb
Update to the latest RISC-V GDB and a patch to fix a compilation error
=> gdb: Update to latest RISC-V fork

conf/machine/freedom-u540.conf, conf/machine/qemuriscv64.conf, recipes-kernel/linux/linux-riscv_4.18.bb
Addresses issue #20
1. fix kernel sanity check.
2. upgrade to config file 4.17 to 4.18-rc7.
- conf/machine/freedom-u540.conf
- conf/machine/qemuriscv64.conf
3. upgrade to kernel bb file 4.17 to 4.18-rc7.
- recipes-kernel/linux/linux-riscv_4.17.bb → recipes-kernel/linux/linux-riscv_4.18.bb  
Update machine kernel version 4.18-rc7 and fix kernel sanity check error
**-Signed-off-by: pino-kim <sungwon.pino@gmail.com>**
=> Update machine kernel version 4.18-rc7

recipes-kernel/linux/linux-riscv_4.14.bb, recipes-kernel/linux/linux-riscv_4.15.bb, recipes-kernel/linux/linux-riscv_4.18.bb
BuildPC OS is Ubuntu 16.04
path: meta-riscv/recipes-kernel/linux/
1. modified kernel version 4.18-rc7 -> 4.18
- My prior PR had kernel build issue. So change below link's commitID kernel build well.
RISC-V Updates for the 4.19 Merge Window
2. modified kernel 4.15 commitid. Because fetch error.
3. create kernel 4.14 bbrecipe.
Update kernel bbrecipe.  
=> Modified kernel bbrecipe commitID and Create Kenrel 4.14 bbrecipe

conf/machine/qemuriscv64.conf, recipes-bsp/u-boot/u-boot_%.bbappend
This patch series uses a fork of u-boot to boot u-boot on the QEMU RISC-V Virt machine.
The patch set is currently pending on upstream u-boot, the status is available here: https://marc.info/?l=u-boot&m=153664145925772&w=2
We don't really need to merge this just yet, I just wanted to have it ready for when the patches are merged.
=> Add support for booting u-boot on QEMU Virt machine

setup.sh
distro append systemd for a init_manager
build well and boot well (by 'runqemu nographic') but stuck long time after bootup.
@kraj give me way to solve this. so append systemd for a init_manager and I can reach commandline.  
M: meta-riscv/setup.sh
All test is in Ubuntu 16.04 clI mode.(not gui).
**-Signed-off-by: pino-kim <sungwon.pino@gmail.com>**
=> Add systemd for distro init manager   (derived from #34 comment)

recipes-bsp/u-boot/u-boot_%.bbappend
We are sort of hijacking OE-Core recipe here, so lets be careful and
make it such that it only happens for risv64, which makes a multi-BSP
scenario work again.
This repo seems to be rebasing :( so add rebaseable=1 so bitbake knows
about it
update to latest rev as of today
=> u-boot: Be mindful of other BSPs when it comes to u-boot overrides

recipes-bsp/u-boot/u-boot_%.bbappend
Now that QEMU RISC-V virt machine support is in master u-boot use the
mainline u-boot instead of a fork.
=> u-boot: Use mainline u-boot

conf/machine/qemuriscv64.conf
In a multi-BSP env u-boot may be provided by other BSP layers as well so
we need to be explicit about u-boot we need
=> qemuriscv64: Express u-boot bootloader choice

recipes-devtools/riscv-tools/files/0002-Makefile.in-Don-t-specify-a-march-if-one-isn-t-speci.patch, recipes-devtools/riscv-tools/riscv-pk.bb
Update to the latest version of the RISC-V Proxy Kernel. This means we
are running an updated bbl.
=> riscv-pk: Update to the latest version

conf/machine/qemuriscv64.conf, recipes-bsp/u-boot/u-boot_%.bbappend
Now that u-boot 2018.11 is supported in Yocto we no longer need custom
options for RISC-V support.
=> u-boot: Remove RISC-V specific version

recipes-support/libgpg-error/files/0001-syscfg-Add-a-riscv32-architecture.patch, recipes-support/libgpg-error/libgpg-error_%.bbappend
This adds support for 32-bit builds to libgpg-error. Upstream status is pending company approval.
Thanks for @pino-kim for helping figure out the patch.
=> libgpg-error: Add support for RISC-V 32-bit

recipes-devtools/riscv-tools/riscv-pk.bb
Bump to the latest bbl version, this fixes the warnings printed by QEMU
on boot.
=> riscv-pk: Bump to the latest version

conf/machine/baremetal-riscv32.conf, conf/machine/baremetal-riscv64.conf
The baremetal machines can't be built as bitbake complains about
riscv32/riscv64 being included twice in the PACKAGE_ARCH variable. To
fix this rename the machines to be different from the architecture.
Also remove the QEMU overrides as these are no longer required.
=> machine: Rename the baremetal machines

recipes-kernel/linux/linux-riscv_4.20.bb
In preperation for the 4.20 kernel release (and to help test) add the
4.20 kernel but don't set it as the default yet.
=> linux: Add the 4.20-rc5 RISC-V kernel

conf/machine/include/arch-riscv.inc
- backport for riscv arch
- Usermode fails with invalid instruction error (for riscv32)
Signed-off-by: pino-kim <sungwon.pino@gmail.com>
=> qemu : Usermode fails with invalid instruction error (for riscv32)

recipes-devtools/riscv-tools/files/0002-Add-libfdt-support.patch, recipes-devtools/riscv-tools/files/0003-Add-microsemi-pcie-entry-in-bbl.patch, recipes-devtools/riscv-tools/files/0004-Rename-bcopy-to-acopy.patch, recipes-devtools/riscv-tools/riscv-pk.bb
Add functionality to bbl to modify the device tree passed to Linux to
specify the MicroSemi PCIe device.
=> riscv-tools: Add support for the MicroSemi PCIe device

recipes-devtools/gdb/gdb-cross-canadian_riscv.bb
This is needed when building gdb from git, in OE-core gdb is built from
tarballs where this issue is not seen, so keep this fix local here
=> gdb-cross-canadian: Add bison-native dependency

conf/machine/include/qemuriscv.inc, conf/machine/qemuriscv32.conf, recipes-kernel/linux/linux-yocto_4.19.bbappend
Default to the mainline 4.19 kernel for the 64-bit QEMU machine.
=> qemuriscv64: Don't use the linux-riscv kernel

conf/machine/qemuriscv64.conf
linux-yocto hangs before it reaches console, until that is
fixed we can not switch
=> qemuriscv64.conf: Pin to linux-riscv again

recipes-bsp/opensbi/opensbi-payloads.inc, recipes-bsp/opensbi/opensbi_0.1.bb
This adds openSBI support. openSBI aims to be the reference
implementation for the M mode firmware. We are going to use it to remove
BBL from the boot flow.
The eventual aim is to have openSBI merged into the meta layer to
support qemuriscv* machines.
Unfortunately openSBI requires a 5.0 kernel, so at the moment we aren't
going to use it.
=> openSBI: Initial commit

recipes-kernel/linux/files/0001-riscv-Partially-revert-Remove-stat64-family-from-def.patch, recipes-kernel/linux/linux-yocto-dev.bbappend
The planned upstream release of 32-bit RISC-V glibc will support statx,
so this patch will not be required in the kernel.
Unfortunately the current 32-bit RISC-V glibc fork does not implement
statx. To allow newer kernels to boot into userspace let's apply this
patch that can be dropped when the glibc port is merged.
=> linux-yocto-dev: Fix missing stat64 system call

conf/machine/freedom-u540.conf
Don't hardcode the Linux version to make it easier to overwrite the
Linux provider. There is only one linux-riscv version so it is not
required.
=> freedom-u540: Don't hardcode linux-version

conf/machine/freedom-u540.conf, recipes-bsp/opensbi/opensbi-payloads.inc, recipes-bsp/u-boot/files/0001-riscv-add-infrastructure-for-calling-functions-on-ot.patch, recipes-bsp/u-boot/files/0001-sifive-fu540-Set-default-arguments-to-help-booting.patch, recipes-bsp/u-boot/files/0002-riscv-import-the-supervisor-binary-interface-header-.patch, recipes-bsp/u-boot/files/0003-riscv-implement-IPI-platform-functions-using-SBI.patch, recipes-bsp/u-boot/files/0004-riscv-delay-initialization-of-caches-and-debug-UART.patch, recipes-bsp/u-boot/files/0005-riscv-save-hart-ID-in-register-tp-instead-of-s0.patch, recipes-bsp/u-boot/files/0006-riscv-add-support-for-multi-hart-systems.patch, recipes-bsp/u-boot/files/0007-riscv-boot-images-passed-to-bootm-on-all-harts.patch, recipes-bsp/u-boot/files/0008-riscv-do-not-rely-on-hart-ID-passed-by-previous-boot.patch, recipes-bsp/u-boot/files/0009-riscv-hang-if-relocation-of-secondary-harts-fails.patch, recipes-bsp/u-boot/files/0010-riscv-fu540-enable-SMP.patch, recipes-bsp/u-boot/files/0011-riscv-qemu-enable-SMP.patch, recipes-bsp/u-boot/files/0012-riscv-Add-a-SYSCON-driver-for-Andestech-s-PLIC.patch, recipes-bsp/u-boot/files/0013-riscv-Add-a-SYSCON-driver-for-Andestech-s-PLMT.patch, recipes-bsp/u-boot/files/0014-riscv-ax25-Add-platform-specific-Kconfig-options.patch, recipes-bsp/u-boot/files/0015-riscv-ax25-Andes-specific-cache-shall-only-support-i.patch, recipes-bsp/u-boot/files/0016-riscv-dts-ae350-support-SMP.patch, recipes-bsp/u-boot/files/0017-riscv-ae350-enable-SMP.patch, recipes-bsp/u-boot/files/0018-riscv-dts-fix-CONFIG_DEFAULT_DEVICE_TREE-failure.patch, recipes-bsp/u-boot/files/tftp-boot.txt, recipes-bsp/u-boot/u-boot_2019.04.bbappend, recipes-kernel/linux/files/freedom-u540/defconfig, wic/freedom-u540-opensbi.wks
This patch series does a few things:
1. Updates the sdcard image to include the standard /boot/ directory. This is common for OE built SD card images. At the moment though as u-boot doesn't support SD/MMC access we can't load the images from here.
2. Add support for SMP boot on the FreedomU540
3. Build u-boot by default and make it easy to set an override to include it as an OpenSBI payload.
4. Setup scripts to help with a TFTP autoboot.
=> Add support for u-boot auto TFTP boot

recipes-kernel/linux/linux-mainline_5.1.bb
Fix the linux-mainline kernel version checks now that we are using
5.1.1.
=> linux-mainline: Fix kernel version checks

conf/machine/freedom-u540.conf, recipes-bsp/u-boot/u-boot_2019.04.bbappend
Ensure that UBOOT_ENTRYPOINT is set correctly for the HiFive Unleased.
=> u-boot: Fix UBOOT_ENTRYPOINT variable setting

.travis.yml
Instead of having a Travis CI system that constantly timesout let's do
two things:
1. Adjust the Travis CI setup to be as fast as possible. By removing as
many commands as we can, avoiding installing too many dependencies and
doing a shallow git clone we can save time.
2. Use timeout to test each major RISC-V machine for 55 minutes. If we
run until we hit the timeout we count the test as a pass. This should
allow use to rely on the tests passing before merging commits while
also testing all three boards.
=> travis: Try to stop builds timing out

conf/machine/freedom-u540.conf, wic/freedom-u540-opensbi.wks
These are patches that do some prepwork for the Linux 5.2, U-Boot 2019.07 and OpenSB 0.4 upgrade. This just does some cleanup in the ``freedom-u540.conf`` file, includes more binaries on the /boot partition and changes the Unleashed boot partition order.
=> Prepare for the Linux 5.2 upgrade

setup.sh
meta-multimedia depends on meta-python.  I'm not sure why it's
necessary to add all the dependent layers in order, but if I don't do
this I get a bunch of exceptions during setup.sh that result in no
meta-python in my bblayers.conf and thus a non-functional bitbake.
setup.sh was already explicitly adding meta-python, so this patch just
adds it before meta-multimedia.  That fixes the errors on my side.
Signed-off-by: Palmer Dabbelt <palmer@sifive.com>
=> Add meta-python before meta-multimedia

recipes-bsp/u-boot/u-boot_2019.07.bbappend
The changes done by this bbappend are all specific to freedom-u540, so
change every override to be machine specific.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> u-boot: change overrides to be specific to freedom-u540

conf/machine/freedom-u540.conf
Based on the default u-boot machine configuration, useful for fitImage
support (known address for loading the device-tree).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> freedom-u540: set UBOOT_DTB_LOADADDRESS

wic/freedom-u540-opensbi-sota.wks
Wic file to be used with sota/ostree (meta-updater), as the source for
root needs to be provided by the otaimage plugin.
It can be maintained outside this layer, but having it maintained at the
official meta-riscv layer makes it a lot easier for users experimenting
with meta-updater.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> wic: add freedom-u540 wic for sota/ostree

conf/machine/freedom-u540.conf
Append causes IMAGE_FSTYPES to contaminate initramfs-based images, as
even when forcing it to be empty at the recipe level, it always shows up
after parsing.
Using += allows the recipe to set another value without being influenced
by the machine configuration.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
=> freedom-u540: prefer += instead of append for IMAGE_FSTYPES

recipes-bsp/u-boot/files/uEnv.txt, recipes-bsp/u-boot/u-boot_2019.07.bbappend
Add the uEnx.txt.in file to meta-riscv to allow users to build OSTree
setups for the HiFive Unleashed. This is based on the original version
from Ricardo Salveti (@ricardosalveti).
=> u-boot: Add OSTree uEnx.txt.in file

recipes-core/glibc/glibc_%.bbappend
Now that OE is using glibc 2.30 and the SRCREV_glibc variable we need to
update our SRCREV.
=> glibc: Fix the glibc SRCREV

conf/layer.conf
It seems to work fine with gcc9 and clang 9
=> Do not disable GCCPIE

conf/layer.conf
=> riscv: Enable SECURITY_CFLAGS and GLIBC PIE for rv32/rv64

conf/machine/qemuriscv32.conf
Now that we are using QEMU 4.1 we can use QEMU's -bios option and
-kernel option and remove the device loader.
=> machine/qemuriscv32: Remove device loader

setup.sh
When building in a non CI env this all is not
needed as the user might accidentally end up losing all the build
artifacts that are not intendeed to. On CI systems its better to delete
it via extra step outside setup
=> setup.sh: Do not delete build dir

conf/machine/baremetal-riscv32.conf, conf/machine/baremetal-riscv64.conf, conf/machine/freedom-u540.conf, conf/machine/qemuriscv32.conf, recipes-devtools/openocd/openocd_riscv.bb
We currently need the RISC-V fork of OpenOCD.
=> openocd: Use the RISC-V fork

conf/machine/qemuriscv32.conf, recipes-core/packagegroups/packagegroup-core-tools-debug.bbappend
Latest glibc wants kernel 5.4+ ABI and linux-yocto is still at 5.2, so
until that switches to 5.4 lets pin to dev kernel which is 5.5+
Fixes #199
=> qemuriscv32: Use linux-yocto-dev for now

recipes-core/packagegroups/packagegroup-go-sdk-target.bbappend, recipes-devtools/go/go-cross-canadian_1.13.bbappend, recipes-devtools/go/go-cross_1.13.bbappend, recipes-devtools/go/go-crosssdk_1.13.bbappend, recipes-devtools/go/go-helloworld_%.bbappend, recipes-devtools/go/go-riscv.inc, recipes-devtools/go/go-runtime_1.13.bbappend, recipes-devtools/go/go/0010-cmd-go-make-content-based-hash-generation-less-pedan.patch, recipes-devtools/go/go_1.13.bbappend
Alter the SRC_URIs to fetch 1.13 from the right fork.
Fixes #114
=> go: Add recipes to support go on riscv64

conf/layer.conf, conf/machine/qemuriscv32.conf, dynamic-layers/virt-layer/recipes-extended/xvisor/xvisor_%.bbappend
Now that Xvisor is supported in [meta-virtulisation](https://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=eb80f0c0ba0c8d088587eb2b1c6e7a561a4768ec) let's add support for the RISC-V specific things we need.
=> Add support for genering Xvisor images

conf/layer.conf
Build QA complains
ERROR: eudev-3.2.9-r0 do_package_qa: QA Issue: eudev: ELF binary /usr/bin/udevadm has relocations in .text
eudev: ELF binary /usr/libexec/udevadm has relocations in .text [textrel]
=> layer.conf: Skip textrel for eudev on rv64

conf/machine/freedom-u540.conf
Fixes
NOTE: Multiple providers are available for virtual/bootloader (u-boot, u-boot-juno, u-boot-orangepi-i96, u-boot-poplar, u-boot-socfpga)
Consider defining a PREFERRED_PROVIDER entry to match virtual/bootloader
=> freedom-u540.conf: Define virtual/bootloader to be u-boot

dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd_riscv.bb
Update the RISC-V fork of OpenOCD to the SHA.
=> openocd: Update to the latest SHA

recipes-core/glibc/glibc_%.bbappend
Update the glibc RV32 to a more recent patch version. Remove some
backported patches that don't apply as we already have them merged.
=> glibc: Update to a later patch version

README.md
No longer support Linux Standard Base (LSB) since version 3.0
core-image-lsb-sdk recipes are removed
So remove the related content
https://www.yoctoproject.org/docs/3.0/ref-manual/ref-manual.html#migration-3.0-lsb-support-removed
Signed-off-by: sungwon.pino <sungwon.pino@gmail.com>
=> README.md : Remove LSB related content that is deprecated

recipes-core/glibc/glibc_%.bbappend
Update to the latest glibc upstream submission. We are very close to having this merged into mainline.
Fixes: https://github.com/riscv/meta-riscv/issues/239
=> glibc: Update to the latest upstream submission

tools/manifests/riscv-yocto.xml
The git:// URLs currently used provide no protection against MITM.
Signed-off-by: Stefan O'Rear <sorear@fastmail.com>
=> Use https URLs to fetch repositories

conf/layer.conf, dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend, dynamic-layers/qt5-layer/recipes-qt/qt5/qtdeclarative_%.bbappend
meta-qt5 now has the same overides upstream, let's remove them for
meta-riscv.
=> qt5-layer: Remove Qt5 overides

recipes-core/musl/musl/0001-Remove-ARMSUBARCH-relic-from-configure.patch, recipes-core/musl/musl/0002-time64-Don-t-make-aliases-to-nonexistent-syscalls.patch, recipes-core/musl/musl/0003-time64-Only-getrlimit-setrlimit-if-they-exist.patch, recipes-core/musl/musl/0004-time64-Only-gettimeofday-settimeofday-if-exist.patch, recipes-core/musl/musl/0005-Add-src-internal-statx.h.patch, recipes-core/musl/musl/0006-Only-call-fstatat-if-defined.patch, recipes-core/musl/musl/0007-Emulate-wait4-using-waitid.patch, recipes-core/musl/musl/0008-riscv-Fall-back-to-syscall-__riscv_flush_icache.patch, recipes-core/musl/musl/0009-riscv32-Target-and-subtarget-detection.patch, recipes-core/musl/musl/0010-riscv32-add-arch-headers.patch, recipes-core/musl/musl/0011-riscv32-Add-fenv-and-math.patch, recipes-core/musl/musl/0012-riscv32-Add-dlsym.patch, recipes-core/musl/musl/0013-riscv32-Add-jmp_buf-and-sigreturn.patch, recipes-core/musl/musl/0014-riscv32-Add-thread-support.patch, recipes-core/musl/musl/0015-Change-definitions-of-F_GETLK-F_SETLK-F_SETLKW.patch, recipes-core/musl/musl/0016-riscv32-Wire-new-syscalls.patch, recipes-core/musl/musl_%.bbappend
Wire new syscalls upto 5.8 kernel for rv32
=> musl: Refresh patch on top of latest musl

conf/layer.conf
python3-matplotlib is now fixed to build for rv32 on meta-python
=> python3-matplotlib,smem: Enable builds for rv32

recipes-core/glibc/glibc_2.32.bbappend
glibc 2.33 is now in OE-Core and supports RV32, so let's remove the 2.32
bbappend.
=> glibc: Remove glibc bbappend

recipes-core/busybox/busybox/0001-hwclock-Check-for-SYS_settimeofday-before-calling-sy.patch, recipes-core/busybox/busybox_1.33%.bbappend, recipes-core/musl/musl/0015-Change-definitions-of-F_GETLK-F_SETLK-F_SETLKW.patch
port on top of oe-core version
=> musl: Update the rv32 patches to apply on latest musl

beaglev.yml, recipes-kernel/linux/linux-starfive/0001-drivers-net-wireless-broadcom-fix-out-of-tree-build.patch, recipes-kernel/linux/linux-starfive_5.10.bb
This helps fix the time issues we were seeing with current config
which was resulting in bad time being reported from kernel and glibc
strftime() tripping over it.
This fixes all those issues and we can boot glibc based rootfs without
issues
=> linux-starfive: Use  starfive_vic7100_evb_sd_net_fedora_defconfig

recipes-bsp/opensbi/opensbi_starfive-0.8.0.bb, recipes-bsp/u-boot/u-boot-starfive_v2021.04.bb
Fedora branch seems to have disappeared ( perhaps renamed to
StarFive_VIC_7100) but StarFive_VIC_7100 is now default branch on github
so lets switch to that
=> opensbi_starfive: Switch to StarFive_VIC_7100 branch name

recipes-kernel/linux/linux-starfive-dev.bb
=> linux-starfive-dev: Use renamed defconfig for beaglev

conf/layer.conf
Latest version is causing QA errors e.g.
ERROR: lttng-tools-2.13.0-r0 do_package_qa: QA Issue: lttng-tools: ELF binary /usr/lib/lttng/libexec/lttng-consumerd has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng-crash has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng-relayd has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng-sessiond has relocations in .text [textrel]
**-Tag …
=> lttng-tools: Skip textrel on rv64

recipes-support/libseccomp/libseccomp_%.bbappend
libseccomp support is not yet upstreamed.
see https://github.com/seccomp/libseccomp/pull/327
=> libseccomp: Use fork for libseccomp on rv32

recipes-support/libseccomp/libseccomp_%.bbappend
This helps to ensure that a valid version is encoded for libseccomp
consumers, We dont need it generally since the release comes from a
release branch but rv32 port is on a staging branch of main where
release number is not coded yet and set to 0.0.0
=> libseccomp: Substitute valid release number

conf/machine/baremetal-riscv32nf.conf
I believe there is a typo in this file, but I would like to double check.
=> baremetal-riscv32nf: Fix typo in syntax override

conf/layer.conf
=> jemalloc: Ignore textrels on rv32 as well

conf/machine/baremetal-riscv32.conf, conf/machine/baremetal-riscv32nf.conf, conf/machine/baremetal-riscv64.conf, setup.sh
image-prelink has been removed in latest yocto ( kirkstone + )
Fixes Issue #325
=> conf: Drop using image-prelink

conf/layer.conf
Fixes
ERROR: apache2-2.4.53-r0 do_package_qa: QA Issue: apache2: ELF binary /usr/sbin/httpd has relocations in .text [textrel]
ERROR: apache2-2.4.53-r0 do_package_qa: Fatal QA errors were found, failing task.
=> apache2: Ignore textrels on rv64

conf/machine/nezha-allwinner-d1.conf, nezha.yml, recipes-bsp/boot0/boot0.bb, recipes-bsp/boot0/files/0001-config.mk-Allow-overriding-CC-and-other-tools.patch, recipes-bsp/boot0/files/0002-config.mk-Remove-nostdinc.patch, recipes-bsp/boot0/files/0003-riscv-fix-build-with-binutils-2.38.patch, recipes-bsp/opensbi/files/0001-lib-utils-fdt-Require-match-data-to-be-const.patch, recipes-bsp/opensbi/files/0002-lib-utils-timer-Add-a-separate-compatible-for-the-D1.patch, recipes-bsp/opensbi/opensbi_%.bbappend, recipes-bsp/u-boot/u-boot-nezha.bb, recipes-bsp/u-boot/u-boot-nezha/0001-riscv-fix-build-with-binutils-2.38.patch, recipes-bsp/u-boot/u-boot-nezha/0001-sun20i-set-CONFIG_SYS_BOOTM_LEN.patch, recipes-bsp/u-boot/u-boot-nezha/toc.cfg, recipes-bsp/u-boot/u-boot-nezha/uEnv-nezha.txt, recipes-kernel/linux/linux-nezha-dev.bb, recipes-kernel/linux/linux-nezha/0001-riscv-fix-build-with-binutils-2.38.patch, wic/nezha.wks
This PR provides early support to the Nezha Allwinner D1 board. It uses **dev** versions of the Linux kernel, U-Boot and OpenSBI. This version was checked and it builds with success.
Key changes:
**- nezha.yml: add file used with kas-docker**
**- linux-nezha-dev | u-boot-nezha | boot0: add patch which fix build with binutils 2.28**
**- nezha.wks: description of SD card image for Nezha D1 development board**
**- linux-nezha-dev: use custom version of kernel with paches for D1 chip**
**- u-boot-nezha: add patch which fix build with binutils 2.28**
**- u-boot-nezha: add patch which increases the CONFIF_SYS_BOOTM_LEN**
**- toc.cfg: add configuration file of TOC1 U-Boot image**
**- uEnv-nezha.txt: U-Boot bootargs for Nezha board**
**- u-boot-nezha.bb: add recipe with patches for Nezha board** …
=> Support of the Nezha Allwinner D1 - Yocto kirkstone

README.md, conf/layer.conf, docs/Plasma-Mobile-on-Unleashed.md, dynamic-layers/openembedded-layer/recipes-devtools/openocd/openocd_riscv.bb, recipes-bsp/u-boot/u-boot-starfive_v2021.04.bb, recipes-devtools/riscv-tools/riscv-fesvr.bb, recipes-devtools/riscv-tools/riscv-spike.bb, recipes-kernel/linux/linux-starfive-dev.bb, recipes-kernel/linux/linux-starfive_5.12.bb
Fixes
QA Issue: libcereal-ptest: ELF binary /usr/lib/libcereal/ptest/tests/test_unordered_multimap has relocations in .text
=> libcereal: Skip textrel QA check on rv32

conf/layer.conf
fixes
ERROR: tgt-1.0.79+gitAUTOINC+b43dbc6711-r0 do_package_qa: QA Issue: tgt: ELF binary /usr/sbin/tgtd has relocations in .text [textrel]
=> tgt: Skip textrel check

recipes-kernel/linux/linux-mainline_5.18.bb
715066a79ea9 riscv: use fallback for random_get_entropy() instead of zero
f4e9fe58d4af riscv: use fallback for random_get_entropy() instead of zero
dcd042ccae9e riscv: dts: sifive: fu540-c000: align dma node name with dtschema
265f34c25bad Merge tag 'riscv-for-linus-5.18-rc8' of git://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux
c932edeaf6d6 riscv: dts: microchip: fix gpio1 reg property typo
b17410182b6f riscv: dts: sifive: fu540-c000: align dma node name with dtschema
26b29404d15c riscv: patch_text: Fixup last cpu should be master
497fe3bb196d Merge tag 'riscv-for-linus-5.18-rc6' of git://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux
2d0de93ca251 Merge tag 'riscv-for-linus-5.18-rc5' of git://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux
6deb9bf4580d riscv: dts: …
=> linux-mainline: bump to 5.18

recipes-bsp/u-boot/u-boot-starfive_v2021.04.bb
The LIC_FILES_CHKSUM md5sum changed with the latest mainline u-boot
release, but hasn't changed for the older starfive release. So manually
specify the original md5sum value.
Resolves: https://github.com/riscv/meta-riscv/issues/350
=> u-boot: starfive_v2021.04: Override the u-boot LIC_FILES_CHKSUM

conf/layer.conf
Fixes build QA
ERROR: libnl-1_3.7.0-r0 do_package_qa: QA Issue: libnl-ptest: ELF binary /usr/lib/libnl/ptest/check-all has relocations in .text [textrel]
ERROR: libnl-1_3.7.0-r0 do_package_qa: Fatal QA errors were found, failing task.
=> libnl: Ignore textrel on rv64/rv32

recipes-bsp/u-boot/u-boot-nezha.bb
The LIC_FILES_CHKSUM md5sum changed with the latest mainline u-boot release. So manually specify the original md5sum value.
Signed-off-by: Matheus Castello <matheus@castello.eng.br>
=> u-boot: nezha: Override the u-boot LIC_FILES_CHKSUM

recipes-bsp/u-boot/u-boot_%.bbappend
This is a generic bbappend and opensbi is riscv specific, so this causes problems when this layer is includes and a build is done for non-riscv machines e.g.
MACHINE=qemumips bitbake -n world
will show the problem
ERROR: Nothing PROVIDES 'opensbi'
opensbi was skipped: incompatible with host mips-yoe-linux-musl (not in COMPATIBLE_HOST) NOTE: Runtime target 'u-boot-default-env' is unbuildable, removing... Missing or unbuildable dependency chain was: ['u-boot-default-env', 'opensbi'] ERROR: Required build target 'meta-world-pkgdata' has no buildable providers. Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'libubootenv', 'u-boot-default-env', 'opensbi']
=> u-boot: Add opensbi do_deploy dep only for machines with opensbi

recipes-bsp/u-boot/u-boot-starfive_v2021.04.bb, recipes-kernel/linux/linux-starfive-dev.bb
It fixes the issue:
https://github.com/riscv/meta-riscv/issues/377
I've faced a fetch issue while baking for Kirkstone. So I updated the linux and u-boot recipe to be the same as in master.
Now, it builds for me.
I don't have the hardware, so I cannot test if it works.
Please, let me know if there is a better version to use on kirkstone.
=> Backport linux uboot from master to kirkstone

recipes-kernel/rtl8723ds-mod/rtl8723ds.bb
It is not intended for all kind of machines by default, other machines can be enabled as needed and verified to work on it.
=> rtl8723ds: Pin to mangopi-mq-pro machine

conf/machine/visionfive2.conf, recipes-bsp/jh7110-spl-tool/jh7110-spl-tool_git.bb, recipes-bsp/opensbi/opensbi/visionfive2-uboot-fit-image.its, recipes-bsp/opensbi/opensbi_%.bbappend, recipes-bsp/u-boot/u-boot-starfive/uEnv-visionfive2.txt, recipes-bsp/u-boot/u-boot-starfive_v2021.10.bb, wic/visionfive2.wks
This PR provides changes to create a bootable Visionfive2 SD card image, similar to the one created in the original Starfive SDK. 
Changes include:
* Add wks file with the partition layout taken from [here](https://github.com/starfive-tech/VisionFive2/blob/JH7110_VisionFive2_devel/conf/genimage-vf2.cfg)
* Add jh7710-spl-tool which is used to generate u-boot-spl.bin.normal.out expected on the SD card by the BootROM
* Deploy visionfive2_fw_payload.img, which is a FIT image containing fw_payload.bin expected by SPL started from SD card
* Update uEnv.txt, so that u-boot-starfive boots fitImage from the partition 3 and rootfs is expected on partition 4 of the SD card 
Current state - SD card flashed with the core-image-minimal-visionfive2.wic using 'dd' or 'bmaptool' boots fine with few …
=> Visionfive2: Build bootable SD card image

wic/visionfive2.wks
Rename the root partition from 'boot' to 'root'.
Signed-off-by: Leonard Anderweit <leonard.anderweit@gmail.com>
=> wic: visionfive2: Fix root partition name

conf/machine/JH7110.inc, conf/machine/star64.conf, conf/machine/visionfive2.conf, recipes-bsp/opensbi/opensbi/visionfive2-uboot-fit-image.its, recipes-bsp/opensbi/opensbi_%.bbappend, recipes-bsp/u-boot/u-boot-starfive/uEnv-star64.txt, recipes-bsp/u-boot/u-boot-starfive_v2021.10.bb, recipes-graphics/drivers/visionfive2-pvr-graphics_1.17.bb, recipes-graphics/xorg-xserver/xserver-xf86-config_%.bbappend, recipes-graphics/xorg-xserver/xserver-xorg_%.bbappend, recipes-kernel/linux/linux-starfive-dev.bb, recipes-kernel/modules/jpu-module.bb, recipes-kernel/modules/vdec-module.bb, recipes-kernel/modules/venc-module.bb, recipes-multimedia/gstreamer/gstreamer1.0-omx_%.bbappend, recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend, recipes-multimedia/vpu/libsf-codaj12.bb, recipes-multimedia/vpu/libsf-omxil.bb, recipes-multimedia/vpu/libsf-wave420l.bb, recipes-multimedia/vpu/libsf-wave511.bb
Several issues with the current visionfive 2 support:
* JH7110 Support is only in OpenSBI Master branch, (upcoming 1.3 release).  So pin OpenSBI Revision to the commit that adds JH7110 Support otherwise reset etc does not work
* There are two variants of VisionFive2 and Star64 - 4Gb and 8Gb. StarFive's u-boot reads the eeprom on board to determine what variant you have, and modifies the loaded FDT it passes to the kernel with the correct Memory. Current U-boot scripts in meta-riscv do not do this, and thus all boards end up with the default 4Gb configuration. I've updated this for Star64, but needs testing on VF2
* Some of the addresses used in uboot for kernel/initramfs or fdt were different from upstream. Aligned the addresses with upstream StarFive.
As both Star64 and VisionFive2 are …
=> Fix VisionFive 2 boot and Add Star64 Board

recipes-bsp/opensbi/opensbi_%.bbappend
This ensures that it does not inflict upon other RISCV SOCs and qemu based machines, which can result in non-booting systems since entry adddress in FW_JUMP Firmware Configuration  is wrong.
=> opensbi: Make FW_TEXT_START=0x40000000 specific to jh7110

recipes-graphics/drivers/visionfive2-pvr-graphics_1.17.bb, recipes-multimedia/vpu/libsf-codaj12/codaj12_yocto.mak, recipes-multimedia/vpu/libsf-wave420l/WaveEncoder_yocto.mak, recipes-multimedia/vpu/libsf-wave511/WaveDecode_yocto.mak
This helps in avoiding conflicts with oe-core provided vulkan-loader recipe
ERROR: The file /usr/lib/libvulkan.so.1 is installed by both visionfive2-pvr-graphics and vulkan-loader, aborting
=> visionfive2: Do not package vulkan prebuilts

conf/machine/JH7110.inc, recipes-bsp/common/visionfive2-firmware.inc, recipes-kernel/linux/linux-starfive-dev.bb, recipes-kernel/linux/linux-starfive/0001-Allow-building-of-PVR-GPU-driver-as-module.patch, recipes-kernel/linux/linux-starfive/visionfive2-graphics.cfg
This small update introduces two main changes:
- update binary blobs and VF2 specific libs to latest SDK (eg. fixes video acceleration, fixes red taint of display output)
- modifies GPU driver to be built as module, which fixes/workarounds a common race condition on Kernel loading when GPU binary blobs are not there then driver is initialized
=> Update VisionFive2 SDK to 3.0.4

recipes-bsp/common/visionfive2-firmware.inc, recipes-kernel/linux/linux-starfive-dev.bb
Update for https://github.com/starfive-tech/VisionFive2/releases/tag/VF2_v3.4.5
=> Update VisionFive2 Firmware to Release v3.4.5

recipes-graphics/drivers/visionfive2-pvr-graphics/rc.pvr.service, recipes-graphics/drivers/visionfive2-pvr-graphics_1.19.bb
This can be used via gcompat coupling at runtime to provide glibc API calls translation to musl.
=> visionfive2-pvr-graphics: Package for musl

recipes-graphics/drivers/visionfive2-pvr-graphics_1.19.bb
As previously [discussed](https://github.com/riscv/meta-riscv/pull/429)
**- visionfive2-pvr-graphics: Fix 'directory not empty' error when systemd folder present**
**-[Affected recipe](https://github.com/riscv/meta-riscv/blob/master/recipes-graphics/drivers/visionfive2-pvr-graphics_1.19.bb)**
**-Fix break in build**
**-Signed-off-by: Owen O'Hehir <oo.hehir@gmail.com>**
=> Fix directory not empty error when systemd folder present

recipes-graphics/drivers/visionfive2-pvr-graphics_1.19.bb, recipes-graphics/wayland/weston_%.bbappend
When using visionfive2 we are using prebuilt blobs for Graphics libraries implementations for GLES1/GLES2 etc. These prebuilts are sadly only build against glibc and have undefined symbols which only glibc knowns about especially versioned ones. We have gcompat library which tries to provide a glue layer for that over musl at runtime, so lets turn a blind eye for link time reports about undefined symbols when building for musl.
**-Signed-off-by: Random J Developer …
=> weston: Ignore undefined symbols in .so on musl/visionfive2

recipes-core/musl/musl/0001-Emulate-wait4-using-waitid.patch, recipes-core/musl/musl/0002-riscv-Fall-back-to-syscall-__riscv_flush_icache.patch, recipes-core/musl/musl/0003-riscv32-Target-and-subtarget-detection.patch, recipes-core/musl/musl/0004-riscv32-add-arch-headers.patch, recipes-core/musl/musl/0005-riscv32-Add-fenv-and-math.patch, recipes-core/musl/musl/0006-riscv32-Add-dlsym.patch, recipes-core/musl/musl/0007-riscv32-Add-jmp_buf-and-sigreturn.patch, recipes-core/musl/musl/0008-riscv32-Add-thread-support.patch, recipes-core/musl/musl/0009-Change-definitions-of-F_GETLK-F_SETLK-F_SETLKW.patch, recipes-core/musl/musl/0010-Add-bits-reg.h-for-riscv32.patch, recipes-core/musl/musl/0011-riscv32-fix-inconsistent-ucontext_t-struct-tag.patch, recipes-core/musl/musl/0012-riscv32-Wire-new-syscalls.patch, recipes-core/musl/musl_%.bbappend
Add newly wired syscalls for riscv32 as well.
=> musl: Sync patches with latest musl tip

conf/machine/milkv-duo.conf
Add milkv-duo-bootfiles to EXTRA_IMAGEDEPENDS so the fip.bin can be found when doing do_image_wic().
Signed-off-by: Yu Chien Peter Lin <mail@yclin.org>
=> milkv-duo: Add bootfile as image dependency

recipes-bsp/common/visionfive2-firmware.inc, recipes-kernel/linux/linux-starfive-dev.bb, recipes-kernel/linux/linux-starfive/0001-gcc-plugins-Fix-build-for-upcoming-GCC-release-kernel61.patch
Upstream now provides to release tracks with supporting both Kernels 5.15 and 6.1. This update uses the 3.9.3 upstream release and switches to the Linux 6.1 Kernel. Basic functionality (including graphics) was tested with a meta-kde demo setup on a Qt6 stack.
=> Update VisionFive2 to Upstream 3.9.3 release and switch to Kernel 6.1

recipes-bsp/common/visionfive2-firmware.inc, recipes-kernel/linux/linux-starfive-dev.bb
Despite the big version number change, this is a small bugfix update by SF mostly with changes for video processing and some fixes around HDMI: https://forum.rvspace.org/t/visionfive2-software-v5-10-3-release/3988
Build and tested successfully on my device with a KDE Plasma Wayland session.
=> Update VisionFive-2 to StarFive SDK release 5.10.3

recipes-bsp/u-boot/u-boot-starfive_v2021.10.bb
u-boot-starfive_v2021.10.bb: The rev 7f96b15e26f1 is no longer on the branch JH7110_VisionFive2_devel, so fetching fails.  This revision is the same as the tag VF2_v3.6.1 so specify nobranch=1 instead of a branch name for this revision.
This resolves the following errors:
WARNING: u-boot-starfive-1_v2021.10-r0 do_fetch: Failed to fetch URL git://github.com/starfive-tech/u-boot.git;protocol=https;branch=JH7110_VisionFive2_devel, attempting MIRRORS if available
ERROR: u-boot-starfive-1_v2021.10-r0 do_fetch: Fetcher failure: Unable to find revision 7f96b15e26f14df56fa9d480c0cc6f7434997360 in branch JH7110_VisionFive2_devel even from upstream
ERROR: u-boot-starfive-1_v2021.10-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', …
=> visionfive2-firmware: Fix visionfive2 U-Boot build

recipes-kernel/linux/linux-allwinnerd1-dev.bb
Compile kernel with -fno-asynchronous-unwind-tables -fno-unwind-tables to fix kernel modules failures [2]. This is workaround until [1] is merged.
[1] https://lore.kernel.org/lkml/20231101-module_relocations-v9-2-8dfa3483c400@rivosinc.com/#r
[2] unknown relocation type 57
=> linux-allwinnerd1-dev:  Fix module loading

recipes-kernel/rtl8723ds-mod/rtl8723ds.bb
If built with gcc 13 module cannot be loaded with [2]. Apply workaround until [1] is merged.
Tested with MangoPi MQ-Pro
[1] https://lore.kernel.org/lkml/20231101-module_relocations-v9-2-8dfa3483c400@rivosinc.com/#r
[2] unknown relocation type 57
=> rtl8723ds: Fix module loading

conf/layer.conf
They compile fine with musl/glibc on rv32 now.
=> capnproto,pidgin-sipe: Re-enable on rv32

recipes-bsp/common/visionfive2-firmware.inc, recipes-bsp/jh7110-spl-tool/jh7110-spl-tool_git.bb, recipes-bsp/u-boot/u-boot-starfive_v2021.10.bb, recipes-kernel/linux/linux-starfive-dev.bb
VisionFive2 JH7110_VF2_6.1_v5.11.3 update
```
Static hostname: visionfive2
Icon name: computer
Machine ID: 843ee583e62542e5a4255df63c21ed19
Boot ID: 8f95fea41d3d4d0398212bf9c938f2bf
Operating System: Poky (Yocto Project Reference Distro) 4.3+snapshot-b5624ee5643d881afa004571a096a189ab5389b5 (scarthgap)
CPE OS Name: cpe:/o:openembedded:poky:4.3+snapshot-b5624ee5643d881afa004571a096a189ab5389b5
Kernel: Linux 6.1.31
Architecture: riscv64
```
[v4l2-info.log](https://github.com/riscv/meta-riscv/files/14733058/v4l2-info.log)
[visionfive2_dmesg.log](https://github.com/riscv/meta-riscv/files/14733060/visionfive2_dmesg.log)
=> VisionFive2 JH7110_VF2_6.1_v5.11.3

recipes-graphics/mesa/mesa-pvr.inc
It conflicts with upstream mesa builds otherwise from core layer, in multi machine build e.g. when builds for qemuriscv64 are done in same project then packaging for mesa-pvr and mesa would conflict since both provide same packages and duplicate file staging errors happen e.g.
ERROR: mesa-pvr-2_22.1.3-r0 do_create_spdx: Recipe mesa-pvr is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
/mnt/b/yoe/master/build/tmp/deploy/spdx/riscv64/packages/libgl-mesa-dev.spdx.json
(matched in manifest-riscv64-mesa.create_spdx)
**-(Optional, if it's not clear …
=> mesa-pvr: Mark it machine arch package

recipes-graphics/drivers/visionfive2-pvr-graphics_1.19.bb
Fix the installation of this recipe when using SysV init system by fixig the "if" condition that checks the presence of systemd in DISTRO_FEATURES - beforehand it was always evaluated as "true".
Beside this the required folders are also created when they should be: in case of SysV init the /usr/bin folder stays empty (and bitbake complains), so it is only created when systemd is used.
Similarly, /etc/init.d is used only by SysV init system, but the recipe already handles it when systemd is used. However if the folder is not installed explicitly, the do_rootfs task fails.
Fixes #473
=> visionfive2-pvr-graphics: fix installation with SysV init

recipes-bsp/u-boot/u-boot-starfive_v2021.10.bb
Fixes 2023.10 build on vf2
| install: cannot stat '/mnt/b/yoe/master/build/tmp/work/visionfive2-yoe-linux/u-boot-starfive/v2021.10/build/boot.scr.uimg': No such file or directory
=> u-boot-starfive: Emit boot.scr.uimg into builddir instead of workdir

recipes-kernel/linux/linux-milkv-duo-dev.bb, recipes-kernel/linux/linux-milkv-duo.bb
Trying to bitbake milkv-duo machine triggers the following error:
| cp: cannot stat 'riscv-yocto/build/tmp/work/milkv_duo-poky-linux/
linux-milkv-duo-dev/1.0/multi.its': No such file or directory
| cp: cannot stat 'riscv-yocto/build/tmp/work/milkv_duo-poky-linux/ linux-milkv-duo/6.8++gitAUTOINC+b95f2066a9/multi.its': No such file or directory
This is caused by multi.its file being in UNPACKDIR instead of WORKDIR, following the recent upstream changes in OE.
=> linux-milkv-duo[-dev]: replace WORKDIR with UNPACKDIR in do_deploy

dynamic-layers/meta-python/recipes-devtools/python/python3-pyruvate_%.bbappend
This is needed after introduction of UNPACKDIR port scarthgap release
=> python3-pyruvate: Use UNPACKDIR to reach patchdir in SRC_URI

kas/include/oe.yml
It will be better to use specific release branch for oe/poky layers instead of master, because currently it throws layer compatibility error. It is similar to oe.yml in meta-riscv kirkstone branch, where branch kirkstone instead of master is used for oe/poky.
At this time, master in poky repo is compatible only with mickledore, scarthgap and nanbield.
=> Use scarthgap branch in oe.yml (fixes scarthgap build)

conf/machine/baremetal-riscv64.conf
Related to #345
Override the `GCCPIE` flag to an empty string in `conf/machine/baremetal-riscv64.conf`.
* Add a comment explaining the reason for the override to support PIE with the elf toolchain.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/riscv/meta-riscv/issues/345?shareId=7217c3a5-3787-409a-a4a0-45c84be606d1).
=> Fix PIE support for baremetal RISC-V

conf/machine/milkv-duo.conf, recipes-bsp/milkv-duo-fsbl/milkv-duo-fsbl.bb, recipes-bsp/u-boot/files/milkv-duo-support-files.patch, wic/milkv-duo-spinand.wks
Related to #487
Add support for creating NAND image for Milk-V Duo in Yocto layer.
* **conf/machine/milkv-duo.conf**
- Add NAND-specific configurations.
- Update `IMAGE_BOOT_FILES` to include `boot.spinand`, `fip.bin`, `rootfs.spinand`, and `system.spinand`.
- Update `WKS_FILE` to use `milkv-duo-spinand.wks`.
* **wic/milkv-duo-spinand.wks**
- Create a new `wic/milkv-duo-spinand.wks` file for NAND image creation.
- Add partitions for `boot.spinand`, `fip.bin`, `rootfs.spinand`, and `system.spinand`.
* **recipes-bsp/u-boot/files/milkv-duo-support-files.patch**
- Add NAND-specific configurations.
- Update `milkv-duo_defconfig` to include NAND support.
* **recipes-bsp/milkv-duo-fsbl/milkv-duo-fsbl.bb**
- Add NAND-specific configurations.
- Update `do_compile` to include NAND-specific …
=> Add NAND support for Milk-V Duo

recipes-kernel/linux/linux-mainline_6.2.bb, recipes-kernel/linux/linux-milkv-duo.bb
By default, the git fetcher protocol will be 'git', this will cause issue when you behind a firewall.
Change them to 'https' will help to resolve these issues.
=> Force the kernel git fecther protocol to be 'https'

recipes-kernel/firmware/linux-firmware-visionfive2-wave511.bb
Add missing firmware `wave511_dec_fw.bin` to recipe `linux-firmware-vision2-wave511`.
Successfully decoded with `h264_v4l2m2m` decoder.
=> Add the missing video decoder wave511 firmware for VisionFive2 

kas/include/local.yml, kas/nezha.yml
Some time ago poky completely dropped "debug-tweaks" from features list [1]. As a result, the latest master can't be built because it tries to enable "debug-tweaks".
To avoid this issue, replace "debug-tweaks" with explicit features as done in Poky.
1 - https://git.yoctoproject.org/poky/commit/?id=43b8b3fa72d75d8d82a478613a4d9bf4645b5389
=> Replace obsolete `debug-tweaks` with explicit feature list

recipes-bsp/u-boot/u-boot-allwinnerd1.bb, recipes-bsp/u-boot/u-boot-allwinnerd1/0002-Fix-build-with-newer-swig.patch
During u-boot-allwinnerd1's configure task, the file boot.scr.uimg gets installed in the sources-unpack/ folder while the install/deploy tasks expect it in the build/ folder.
In addition the newer Python version is not compatible anymore with this u-boot version. I added a patch back ported from upstream u-boot that fixes this.
I will try to open a MR with this back ported patch to the u-boot fork used for AllWinner D1. Doesn't seem to be actively maintained, still worth a try
Tested generating and running on a mangopi-mq-pro, both against poki's master and walnascar branches.
Attached full boot log on a mangopi-mq-pro:
[mangopi-mq-pro_fullboot_master.log](https://github.com/user-attachments/files/19702327/mangopi-mq-pro_fullboot_master.log)
I'm still learning Yocto, so not sure about the …
=> [U-Boot][AllWinnerD1] Fix build of u-boot

recipes-bsp/u-boot/u-boot-allwinnerd1.bb
On the `Styhead` branch, during `u-boot-allwinnerd1`'s configure task, the file `boot.scr.uimg` gets installed in the `sources-unpack/` folder while the install/deploy tasks expect it in the `build/` folder, thus the build fails
This MR fixes the configure role to generate this file in the `build/` folder.
Tested generating both `mangopi-mq-pro` and `nezha` images that previously failed.
Attached full boot log on a mangopi-mq-pro:
[mangopi-mq-pro_fullboot_styhead.log](https://github.com/user-attachments/files/19639346/mangopi-mq-pro_fullboot_styhead.log)
Same fix might also be required on some other machines.
=> [Styhead][U-Boot][AllWinnerD1] Fix folder for boot.scr.uimg

recipes-bsp/opensbi/opensbi_%.bbappend
Edit opensbi recipe to fetch opensbi from revyos to get th1520 downstream-support
- fixes secondaries CPUs unable to come online (at least for the latest kernels) #529
=> beaglev-ahead: opensbi fix to get 4 online CPUs

recipes-kernel/linux/linux-starfive-dev.bb
This kernel is 6.6 and upstream linux-yocto kernel cache has added KERNEL_FEATURES_RISCV kernel features to 6.12 branch onwards and has started using it in linux-yocto.inc which is used by this recipe
Remove these scc files until this kernel moves to 6.12+ and metadata branch is updated accordingly as well.
Upgrade yocto-kernel-cache/6.6 to latest tip while here.
=> linux-starfive-dev: Remove KERNEL_FEATURES_RISCV

recipes-bsp/common/visionfive2-firmware.inc
Do not encode it in rev= param in SRC_URI, this fails with lfs enabled
WARNING: linux-firmware-visionfive2-imggpu-1.0-r0 do_fetch: Fetching LFS did not succeed.
=> visionfive2-firmware.inc: Specify revision using SRCREV

recipes-bsp/common/visionfive2-firmware.inc
This reverts commit 1cb6c4a83c53480d38e18598afa01ed99a60ace4.
its just a fork, so LFS limits still account towards owner handle and problem persists.
=> Revert "visionfive2-firmware: Point to strlcat.eu mirror"
